In [29]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import precision_score, recall_score

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

## 1. Decision Tree: Overfitting vs Underfitting

In [2]:
df = load_iris(as_frame=True).frame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [3]:
X = df.drop(['target'], axis=1)
y = df['target']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [5]:
model_A = DecisionTreeClassifier(max_depth=2, min_samples_split=5)
model_A.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2, min_samples_split=5)

In [6]:
model_B = DecisionTreeClassifier()
model_B.fit(X_train, y_train)

DecisionTreeClassifier()

In [7]:
print(f"Model A Training accuracy: {model_A.score(X_train, y_train)}")
print(f"Model A Testing accuracy: {model_A.score(X_test, y_test)}")

Model A Training accuracy: 0.9666666666666667
Model A Testing accuracy: 0.9333333333333333

In [8]:
print(f"Model B Training accuracy: {model_B.score(X_train, y_train)}")
print(f"Model B Testing accuracy: {model_B.score(X_test, y_test)}")

Model B Training accuracy: 1.0
Model B Testing accuracy: 0.9333333333333333

In [9]:
for depth in range(1, 10):
    model = DecisionTreeClassifier(max_depth=depth, random_state=42)
    model.fit(X_train, y_train)
    print(f"depth={depth}, train={model.score(X_train, y_train):.3f}, test={model.score(X_test, y_test):.3f}")

depth=1, train=0.667, test=0.667
depth=2, train=0.967, test=0.933
depth=3, train=0.983, test=0.967
depth=4, train=0.992, test=0.933
depth=5, train=1.000, test=0.933
depth=6, train=1.000, test=0.933
depth=7, train=1.000, test=0.933
depth=8, train=1.000, test=0.933
depth=9, train=1.000, test=0.933

## 2. Finding the Best Tree Depth

In [10]:
df = pd.read_csv('winequality-red.csv')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [11]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [12]:
X = df.drop(['quality'], axis=1)
y = df['quality']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [14]:
model = DecisionTreeClassifier()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.20      0.18      0.19        11
           5       0.70      0.70      0.70       136
           6       0.60      0.58      0.59       128
           7       0.60      0.65      0.63        40
           8       0.12      0.33      0.18         3

    accuracy                           0.62       320
   macro avg       0.37      0.41      0.38       320
weighted avg       0.62      0.62      0.62       320

In [15]:
model_1 = DecisionTreeClassifier(max_depth=2)
model_1.fit(X_train, y_train)

# training data accuracy
y_pred_train = model_1.predict(X_train)
print(f"Training data accuracy: {accuracy_score(y_train, y_pred_train)}")

# testing data accuracy
y_pred_test = model_1.predict(X_test)
print(f"Testing accuracy: {accuracy_score(y_test, y_pred_test)}")

Training data accuracy: 0.5699765441751369
Testing accuracy: 0.5125

In [16]:
model_2 = DecisionTreeClassifier(max_depth=4)
model_2.fit(X_train, y_train)

# training data accuracy
y_pred_train = model_2.predict(X_train)
print(f"Training data accuracy: {accuracy_score(y_train, y_pred_train)}")

# testing data accuracy
y_pred_test = model_2.predict(X_test)
print(f"Testing accuracy: {accuracy_score(y_test, y_pred_test)}")

Training data accuracy: 0.6301798279906177
Testing accuracy: 0.5625

In [17]:
model_3 = DecisionTreeClassifier(max_depth=6)
model_3.fit(X_train, y_train)

# train
y_pred_train = model_3.predict(X_train)
print(f"Train acc: {accuracy_score(y_train, y_pred_train)}")

# test
y_pred_test = model_3.predict(X_test)
print(f"Test acc: {accuracy_score(y_test, y_pred_test)}")

Train acc: 0.7122752150117279
Test acc: 0.575

In [18]:
model_4 = DecisionTreeClassifier(max_depth=8)
model_4.fit(X_train, y_train)

# train
y_pred_train = model_4.predict(X_train)
print(f"Train acc: {accuracy_score(y_train, y_pred_train)}")

# test
y_pred_test = model_4.predict(X_test)
print(f"Test acc: {accuracy_score(y_test, y_pred_test)}")

Train acc: 0.8021892103205629
Test acc: 0.571875

In [19]:
model_4 = DecisionTreeClassifier(max_depth=None)
model_4.fit(X_train, y_train)

# train
y_pred_train = model_4.predict(X_train)
print(f"Train acc: {accuracy_score(y_train, y_pred_train)}")

# test
y_pred_test = model_4.predict(X_test)
print(f"Test acc: {accuracy_score(y_test, y_pred_test)}")

Train acc: 1.0
Test acc: 0.603125

In [20]:
for depth in range(1, 10):
  model = DecisionTreeClassifier(max_depth=depth, random_state=42)
  model.fit(X_train, y_train)
  print(f"Depth={depth}, train={model.score(X_train, y_train):.3f}, test={model.score(X_test, y_test):.3f}")

Depth=1, train=0.568, test=0.531
Depth=2, train=0.570, test=0.512
Depth=3, train=0.578, test=0.522
Depth=4, train=0.630, test=0.562
Depth=5, train=0.660, test=0.584
Depth=6, train=0.712, test=0.575
Depth=7, train=0.760, test=0.578
Depth=8, train=0.802, test=0.581
Depth=9, train=0.854, test=0.588

## 3. Random Forest vs Decision Tree

In [21]:
df = pd.read_csv("Breast Cancer Wisconsin.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [22]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [23]:
df.shape

(569, 33)

In [24]:
df.drop('Unnamed: 32',axis=1, inplace=True)

In [25]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [26]:
X = df.drop(['diagnosis', 'id'], axis=1)
y = df['diagnosis']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [30]:
# Random Forest

grid_param = {
    "n_estimators" : [100],
    "criterion" : ['gini', 'entropy'],
    "max_features" : ['sqrt', 'log2']
}

grid_search_RF = GridSearchCV(
    estimator = RandomForestClassifier(),
    param_grid = grid_param,
    cv = 5
)

grid_search_RF.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [100]})

In [40]:
# y_pred_train = grid_search_RF.predict(X_train)
# print(f"Training Accuracy: {accuracy_score(y_train, y_pred_train)}")

y_pred = grid_search_RF.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)
precision = precision_score(y_test, y_pred, pos_label='M')
print(precision)
print(recall_score(y_test, y_pred, pos_label='M'))

0.9649122807017544
1.0
0.9047619047619048

In [32]:
y_pred = grid_search_RF.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           B       0.95      1.00      0.97        72
           M       1.00      0.90      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.95      0.96       114
weighted avg       0.97      0.96      0.96       114

## 4. Effect of Number of Trees

In [41]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [44]:
X = df.drop(['target'], axis=1)
y = df['target']

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [47]:
# rain Random Forest with Different Numbers of Trees

import time

result = []
trees = [10, 50, 100, 200]

for n in trees:
  start = time.time()
  model = RandomForestClassifier(
      n_estimators = n,
      random_state = 42
  )

  model.fit(X_train, y_train)
  end = time.time()

  train_acc = accuracy_score(y_train, model.predict(X_train))
  test_acc = accuracy_score(y_test, model.predict(X_test))

  result.append([
      n,
      train_acc,
      test_acc,
      end - start
  ])

In [48]:
comparison = pd.DataFrame(
    result,
    columns=[
        "Number of trees",
        "Train Accuracy",
        "Test Accuracy",
        "Training Time (sec)"
    ]
)

comparison

   Number of trees  Train Accuracy  Test Accuracy  Training Time (sec)
0               10             1.0            1.0             0.033340
1               50             1.0            1.0             0.098589
2              100             1.0            1.0             0.214182
3              200             1.0            1.0             0.400373