# Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
len(df.columns)

31

In [ ]:
X_train

array([[ 1.68824786,  1.0687997 ,  1.75677388, ...,  1.17605607,
         0.63846991,  0.60791824],
       [-0.85956498,  0.74332119, -0.85042177, ..., -0.77465196,
         0.43832343, -0.18715906],
       [ 1.11669609,  0.60579505,  1.04320823, ..., -0.35337086,
        -0.84261404, -1.00270807],
       ...,
       [-0.29654384, -0.83364513, -0.2020257 , ...,  1.27194013,
         0.40309765,  3.14253835],
       [ 0.03330693,  0.76853431,  0.0685518 , ...,  0.3222313 ,
        -0.31582851, -0.01065964],
       [ 2.54131019,  0.14508251,  2.47446418, ...,  1.69504759,
         0.02041758, -0.60489278]])

In [ ]:
y_train

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [ ]:
X_train

array([[ 1.68824786,  1.0687997 ,  1.75677388, ...,  1.17605607,
         0.63846991,  0.60791824],
       [-0.85956498,  0.74332119, -0.85042177, ..., -0.77465196,
         0.43832343, -0.18715906],
       [ 1.11669609,  0.60579505,  1.04320823, ..., -0.35337086,
        -0.84261404, -1.00270807],
       ...,
       [-0.29654384, -0.83364513, -0.2020257 , ...,  1.27194013,
         0.40309765,  3.14253835],
       [ 0.03330693,  0.76853431,  0.0685518 , ...,  0.3222313 ,
        -0.31582851, -0.01065964],
       [ 2.54131019,  0.14508251,  2.47446418, ...,  1.69504759,
         0.02041758, -0.60489278]])

In [ ]:
type(y_train)

numpy.ndarray

In [ ]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [ ]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_1394/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_1394/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_1394/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_1394/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [ ]:
type(X_train_tensor)

torch.Tensor

# Dataset & Dataloader

In [42]:
from torch.utils.data import Dataset, DataLoader

In [51]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [52]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [53]:
len(train_dataset)

455

In [54]:
train_dataset[2]

(tensor([ 1.1167,  0.6058,  1.0432,  1.0371, -1.6405, -0.3248,  0.2823,  0.2291,
         -0.1213, -1.3373,  0.8128,  0.1664,  0.6926,  0.7455, -0.4562,  1.5842,
          1.1038,  0.4583,  0.1088,  0.5813,  0.7092, -0.1467,  0.6407,  0.5933,
         -1.9254, -0.3627, -0.0864, -0.3534, -0.8426, -1.0027]),
 tensor(1.))

# Loader

In [55]:
train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = True)

# Defining the Model

In [56]:
X_train.shape[1]

30

In [57]:
import torch.nn as nn

In [58]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [59]:
torch.rand(30,1)

tensor([[0.5767],
        [0.7678],
        [0.1263],
        [0.3697],
        [0.3560],
        [0.7300],
        [0.5029],
        [0.7638],
        [0.7551],
        [0.1754],
        [0.5004],
        [0.0290],
        [0.5363],
        [0.4183],
        [0.6281],
        [0.1725],
        [0.5045],
        [0.4274],
        [0.4869],
        [0.0735],
        [0.5920],
        [0.3938],
        [0.6444],
        [0.8709],
        [0.8436],
        [0.9003],
        [0.5972],
        [0.7823],
        [0.0805],
        [0.3680]])

# Parameters

In [ ]:
X_train_tensor.shape[1]

30

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [ ]:
model = MySimpleNN(X_train_tensor.shape[1])

In [ ]:
model.parameters()

In [ ]:
X_test_tensor.dtype

torch.float32

In [ ]:
model.linear.weight.dtype

torch.float32

In [ ]:
y_train_tensor.dtype

torch.float32

In [ ]:
model.parameters()

# Training Pipeline

In [60]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature, batch_label in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_label.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()
    #parameter update
    optimizer.step()


  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.3670682907104492
 2 , Loss = 0.16853082180023193
 3 , Loss = 0.07442313432693481
 4 , Loss = 0.15750636160373688
 5 , Loss = 0.025355618447065353
 6 , Loss = 0.05876440927386284
 7 , Loss = 0.15545082092285156
 8 , Loss = 0.11351338773965836
 9 , Loss = 0.07756399363279343
 10 , Loss = 0.05452752113342285
 11 , Loss = 0.06011129170656204
 12 , Loss = 0.07173911482095718
 13 , Loss = 0.09235967695713043
 14 , Loss = 0.0813203826546669
 15 , Loss = 0.03845721855759621
 16 , Loss = 0.1463402658700943
 17 , Loss = 0.02123064361512661
 18 , Loss = 0.031528450548648834
 19 , Loss = 0.00998083408921957
 20 , Loss = 0.039103951305150986
 21 , Loss = 0.03559514880180359
 22 , Loss = 0.009200016036629677
 23 , Loss = 0.015143766067922115
 24 , Loss = 0.0010423781350255013
 25 , Loss = 0.07793403416872025

# Training pipeline version 2

In [61]:
# Create model

model = MySimpleNN(X_train_tensor.shape[1])

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs):

  for start_indx in range(0, n_sample, batch_size):
    end_indx = start_indx + batch_size

    # print(f"Start index {start_indx}, end index {end_indx}")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    # forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred, y_batch.reshape(-1, 1))

    # update step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print(f"{epoch+1}, Loss = {loss.item()}")

1, Loss = 0.22166235744953156
2, Loss = 0.16705532371997833
3, Loss = 0.13932760059833527
4, Loss = 0.1215970516204834
5, Loss = 0.10900691896677017
6, Loss = 0.09946728497743607
7, Loss = 0.09191498905420303
8, Loss = 0.08574577420949936
9, Loss = 0.08058737963438034
10, Loss = 0.07619564235210419
11, Loss = 0.07240244001150131
12, Loss = 0.06908756494522095
13, Loss = 0.06616214662790298
14, Loss = 0.06355885416269302
15, Loss = 0.06122562661767006
16, Loss = 0.059121280908584595
17, Loss = 0.05721291899681091
18, Loss = 0.055473752319812775
19, Loss = 0.053881797939538956
20, Loss = 0.05241876468062401
21, Loss = 0.05106937140226364
22, Loss = 0.0498206727206707
23, Loss = 0.04866161569952965
24, Loss = 0.047582753002643585
25, Loss = 0.046575915068387985

# Model Evaluation ( old )

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5669436454772949

# Batter version

In [62]:
model.eval()  # evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    # print(y_pred)
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

tensor(0.9705)

In [63]:
accuracy_list

[tensor(0.9688), tensor(1.), tensor(0.9688), tensor(0.9444)]

# Summary

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [ ]:
from torchinfo import summary

In [ ]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================