In [44]:
a = 10
print(a)
print(type(a))

10
<class 'int'>

In [45]:
# time

from datetime import datetime

now = datetime.now()

# convert to sting
date_str = now.strftime("%Y-%m-%d %H:%M:%S")
print(type(date_str))

<class 'str'>

# List and LOOP

In [3]:
nums = input().split()

even_sum = 0
even_count = 0

for num in nums:
    num = int(num)

    if num % 2 == 0:
        even_sum += num
        even_count += 1

 1 2 3 4

In [9]:
nums = list(map(int, input().split()))

even_sum = 0
even_count = 0

for num in nums:
    num = int(num)

    if num % 2 == 0:
        even_sum += num
        even_count += 1

 1 2 3 4

In [12]:
even_sum

6

# Dictionary

In [16]:
numbers = input().split()

freq = {}

for num in numbers:
    num = int(num)
    
    if num in freq:
        freq[num] += 1
    else:
        freq[num] = 1

print(freq)

 1 2 2 3 1 2

{1: 2, 2: 3, 3: 1}

In [17]:
# example 2

import numpy as np
import pandas as pd

# create numpy array
names = np.array(["Alice", "BOB", "Charlie", "David"])
scores = np.array([88, 98, 97, 85])

# create dectionary

data = {
    "Name" : names,
    "Scores": scores 
}

# convert to pandas DataFrame
df = pd.DataFrame(data)

In [18]:
df

      Name  Scores
0    Alice      88
1      BOB      98
2  Charlie      97
3    David      85

# Function

# Iterator

In [21]:
import numpy as np 
import pandas as pd

# iterator
arr = np.array([10, 20, 30, 40, 50])
arr_iter = iter(arr)

print(next(arr_iter))
print(next(arr_iter))
print(next(arr_iter))
print(next(arr_iter))
print(next(arr_iter))

10
20
30
40
50

In [22]:
df = pd.DataFrame(
    {
        "A" : [1, 2, 3],
        "B" : [4, 5, 6]
    }
)

In [23]:
df

   A  B
0  1  4
1  2  5
2  3  6

In [24]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, A=1, B=4)
Pandas(Index=1, A=2, B=5)
Pandas(Index=2, A=3, B=6)

# Generator

In [42]:
def data_loader(batch_size, data):

    for i in range(0, len(data), batch_size):    # yield return chunk data, not whole data
        yield data[i : i+batch_size]

data = np.arange(20)

loader = data_loader(5, data)

print(next(loader))
print(next(loader))
print(next(loader))
print(next(loader))

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]

In [43]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Filter

In [34]:
import numpy as np
import pandas as pd

data = np.array([10, 15, 20, 25, 30])

filtered_np = list(filter(lambda x: x>20, data))

In [37]:
print(*filtered_np)

25 30

In [41]:
df = pd.DataFrame(
    {
        "name" : ["Alice", "BOB"],
        "Score" : [85, 991]
    }
)

hight_score = df[df['Score'] > 80]
print(hight_score)

    name  Score
0  Alice     85
1    BOB    991